{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove)\n",
    "from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters, RegexHandler,\n",
    "                          ConversationHandler)\n",
    "import requests\n",
    "import logging\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "mapping_target = {\n",
    "    'A': 0,\n",
    "    'A+': 1,\n",
    "    'B': 2,\n",
    "    'C': 3\n",
    "}\n",
    "\n",
    "ddd = {}\n",
    "for k, v in mapping_target.items():\n",
    "    ddd[float(v)] = k\n",
    "    \n",
    "df = pd.read_csv('v2.csv')\n",
    "df['object_class_fixed'] = df.object_class_fixed.apply(lambda x:ddd[x])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# df[df['latitude'] == np.inf]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def _parse(d, path, i=0):\n",
    "\n",
    "    if isinstance(path, str):\n",
    "        path = path.split(':')\n",
    "\n",
    "    if i == len(path):\n",
    "        return d\n",
    "\n",
    "    for j in range(len(path)):\n",
    "        if path[i + j].isdigit():\n",
    "            path[i + j] = int(path[i + j])\n",
    "\n",
    "        d = d[path[i + j]]\n",
    "        return _parse(d, path, i=i+1)\n",
    "\n",
    "def parse(d, path):\n",
    "\n",
    "    try:\n",
    "        return _parse(d, path)\n",
    "    except Exception as e:\n",
    "        print('some error during path travesing: {}'.format(e))\n",
    "        return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "from telegram import ReplyKeyboardMarkup\n",
    "from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters, RegexHandler,\n",
    "                          ConversationHandler)\n",
    "\n",
    "import logging\n",
    "\n",
    "# Enable logging\n",
    "logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "                    level=logging.INFO)\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "CHOOSING, TYPING_REPLY, TYPING_CHOICE = range(3)\n",
    "\n",
    "reply_keyboard = [['Адрес', 'FAQ'],\n",
    "                  ['Done']]\n",
    "markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)\n",
    "\n",
    "\n",
    "def facts_to_str(user_data):\n",
    "    facts = list()\n",
    "\n",
    "    for key, value in user_data.items():\n",
    "        facts.append('{} - {}'.format(key, value))\n",
    "\n",
    "    return \"\\n\".join(facts).join(['\\n', '\\n'])\n",
    "\n",
    "\n",
    "def start(bot, update):\n",
    "    update.message.reply_text(\n",
    "        \"Найду инфу по классу недвижки и еще много стафа\",\n",
    "        reply_markup=markup)\n",
    "\n",
    "    return CHOOSING\n",
    "\n",
    "\n",
    "def regular_choice(bot, update, user_data):\n",
    "    text = update.message.text\n",
    "    user_data['choice'] = text\n",
    "    update.message.reply_text(\n",
    "        'Ваш {}? Нужно понять, что мне делать!'.format(text.lower()))\n",
    "\n",
    "    return TYPING_REPLY\n",
    "\n",
    "\n",
    "# def custom_choice(bot, update):\n",
    "#     update.message.reply_text('Alright, please send me the category first, '\n",
    "#                               'for example \"Most impressive skill\"')\n",
    "\n",
    "#     return TYPING_CHOICE\n",
    "\n",
    "from math import cos, asin, sqrt\n",
    "\n",
    "def distance(lat1, lon1, lat2, lon2):\n",
    "    p = 0.017453292519943295\n",
    "    a = 0.5 - cos((lat2-lat1)*p)/2 + cos(lat1*p)*cos(lat2*p) * (1-cos((lon2-lon1)*p)) / 2\n",
    "    return 12742 * asin(sqrt(a))\n",
    "\n",
    "\n",
    "# * longitude 'геокоординаты долгота'\n",
    "# * latitude 'геокоординаты широта'\n",
    "\n",
    "def closest(data, v):\n",
    "    \n",
    "    minim = np.inf\n",
    "    min_row = None\n",
    "    for i, row in data.iterrows():\n",
    "        dist = distance(v['latitude'], v['longitude'], row['latitude'], row['longitude'])\n",
    "        if dist < minim:\n",
    "            minim = dist\n",
    "            min_row = row\n",
    "    return min_row\n",
    "            \n",
    "# tempDataList = [{'lat': 39.7612992, 'lon': -86.1519681}, \n",
    "#                 {'lat': 39.762241,  'lon': -86.158436 }, \n",
    "#                 {'lat': 39.7622292, 'lon': -86.1578917}]\n",
    "\n",
    "# v = {'lat': 39.7622290, 'lon': -86.1519750}\n",
    "# print(closest(tempDataList, v))\n",
    "\n",
    "\n",
    "def received_information(bot, update, user_data):\n",
    "    text = update.message.text\n",
    "    category = user_data['choice']\n",
    "    user_data[category] = text\n",
    "    del user_data['choice']\n",
    "    \n",
    "    r = requests.get('https://geocode-maps.yandex.ru/1.x/?geocode={}&format=json'.format(text)).json()\n",
    "    \n",
    "    found = parse(r, path='response:GeoObjectCollection:metaDataProperty:GeocoderResponseMetaData:found')\n",
    "    if found == 0:\n",
    "        \n",
    "\n",
    "        update.message.reply_text(\"Угараете? Не представляю где такое ищут\", reply_markup=markup)\n",
    "        \n",
    "    else:\n",
    "\n",
    "        update.message.reply_text(\"Что - то дайте подумать на этим:\"\n",
    "                                  \"{}\"\n",
    "                                  \"Нужно глянуть в бдшечку.\".format(facts_to_str(user_data)), reply_markup=markup)\n",
    "        \n",
    "        data_pos = parse(r, path='response:GeoObjectCollection:featureMember:0:GeoObject:Point:pos')\n",
    "        if data_pos:\n",
    "#             try:\n",
    "            lat, lon = map(np.float, data_pos.split(' '))\n",
    "            update.message.reply_text(\"вот эта точка\"\n",
    "                                      \" {} \"\n",
    "                                      \"\".format(data_pos), reply_markup=markup)\n",
    "                \n",
    "            v = {'latitude': lat, 'longitude': lon}\n",
    "            print(v)\n",
    "            update.message.reply_text(\"вот это вот\"\n",
    "                                      \" {} \"\n",
    "                                      \"\".format(closest(df, v)), reply_markup=markup)\n",
    "\n",
    "                \n",
    "                \n",
    "#             except:\n",
    "#                 update.message.reply_text(\"Сложно что-то координаты определить\", reply_markup=markup)\n",
    "                \n",
    "    \n",
    "\n",
    "    return CHOOSING\n",
    "\n",
    "\n",
    "def done(bot, update, user_data):\n",
    "    if 'choice' in user_data:\n",
    "        del user_data['choice']\n",
    "\n",
    "    update.message.reply_text(\"Понял:\"\n",
    "                              \"{}\"\n",
    "                              \"До скорого!\".format(facts_to_str(user_data)))\n",
    "\n",
    "    user_data.clear()\n",
    "    return ConversationHandler.END\n",
    "\n",
    "\n",
    "def error(bot, update, error):\n",
    "    \"\"\"Log Errors caused by Updates.\"\"\"\n",
    "    logger.warning('Update \"%s\" caused error \"%s\"', update, error)\n",
    "\n",
    "\n",
    "def main():\n",
    "    # Create the Updater and pass it your bot's token.\n",
    "    updater = Updater(\"503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c\")\n",
    "\n",
    "    # Get the dispatcher to register handlers\n",
    "    dp = updater.dispatcher\n",
    "\n",
    "    # Add conversation handler with the states GENDER, PHOTO, LOCATION and BIO\n",
    "    conv_handler = ConversationHandler(\n",
    "        entry_points=[CommandHandler('start', start)],\n",
    "\n",
    "        states={\n",
    "            CHOOSING: [RegexHandler('^(Адрес|FAQ)$',\n",
    "                                    regular_choice,\n",
    "                                    pass_user_data=True),\n",
    "                       ],\n",
    "\n",
    "            TYPING_CHOICE: [MessageHandler(Filters.text,\n",
    "                                           regular_choice,\n",
    "                                           pass_user_data=True),\n",
    "                            ],\n",
    "\n",
    "            TYPING_REPLY: [MessageHandler(Filters.text,\n",
    "                                          received_information,\n",
    "                                          pass_user_data=True),\n",
    "                           ],\n",
    "        },\n",
    "\n",
    "        fallbacks=[RegexHandler('^Ясненько$', done, pass_user_data=True)]\n",
    "    )\n",
    "\n",
    "    dp.add_handler(conv_handler)\n",
    "\n",
    "    # log all errors\n",
    "    dp.add_error_handler(error)\n",
    "\n",
    "    # Start the Bot\n",
    "    updater.start_polling()\n",
    "\n",
    "    # Run the bot until you press Ctrl-C or the process receives SIGINT,\n",
    "    # SIGTERM or SIGABRT. This should be used most of the time, since\n",
    "    # start_polling() is non-blocking and will stop the bot gracefully.\n",
    "    updater.idle()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2018-02-18 16:35:37,319 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:35:37,320 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:43:06,914 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:43:06,916 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:43:20,261 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:43:20,262 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:43:34,027 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:43:34,028 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:44:10,400 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:44:10,401 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:44:23,680 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:44:23,681 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:45:07,693 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:45:07,694 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:46:14,679 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:46:14,680 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:47:20,023 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:47:20,024 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:48:24,840 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 16:48:24,841 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 16:48:43,906 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63e10>: Failed to establish a new connection: [Errno 65] No route to host',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:43,917 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63f60>: Failed to establish a new connection: [Errno 65] No route to host',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:43,919 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e633c8>: Failed to establish a new connection: [Errno 65] No route to host',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:43,922 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63a90>: Failed to establish a new connection: [Errno 65] No route to host',))\n",
      "2018-02-18 16:48:43,923 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63a90>: Failed to establish a new connection: [Errno 65] No route to host',))\"\n",
      "2018-02-18 16:48:45,433 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63b70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:45,435 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:45,437 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63898>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates\n",
      "2018-02-18 16:48:45,438 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))\n",
      "2018-02-18 16:48:45,439 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot503183548:AAEx9UHfJXbdXl8kIhPxOJAjr0ejk8RIp5c/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x117e63390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))\"\n",
      "2018-02-18 16:48:48,349 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:48:48,350 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:48:51,792 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:48:51,795 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:48:56,901 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:48:56,910 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:49:04,532 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:49:04,536 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:49:16,076 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:49:16,080 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:50:31,619 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:50:31,622 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:50:57,294 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2018-02-18 16:50:57,297 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 16:52:57,408 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\n",
      "2018-02-18 16:52:57,410 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:748)\"\n",
      "2018-02-18 17:50:48,106 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 17:50:48,109 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 17:51:30,288 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 17:51:30,290 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:00:10,384 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:00:10,385 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:04:48,996 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:04:48,997 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:05:54,569 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:05:54,571 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:16:25,805 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:16:25,806 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:18:09,817 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:18:09,818 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:25:09,753 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:25:09,754 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:25:22,938 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:25:22,940 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:30:21,758 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:30:21,759 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:42:14,159 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:42:14,161 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:43:18,933 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:43:18,934 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 18:43:32,145 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 18:43:32,146 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n",
      "2018-02-18 19:08:27,688 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out\n",
      "2018-02-18 19:08:27,689 - __main__ - WARNING - Update \"None\" caused error \"Timed out\"\n"
     ]
    }
   ],
   "source": [
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python3 ml_env",
   "language": "python",
   "name": "ml_enc"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.2"
  },
  "toc": {
   "colors": {
    "hover_highlight": "#DAA520",
    "navigate_num": "#000000",
    "navigate_text": "#333333",
    "running_highlight": "#FF0000",
    "selected_highlight": "#FFD700",
    "sidebar_border": "#EEEEEE",
    "wrapper_background": "#FFFFFF"
   },
   "moveMenuLeft": true,
   "nav_menu": {
    "height": "12px",
    "width": "252px"
   },
   "navigate_menu": true,
   "number_sections": true,
   "sideBar": true,
   "threshold": 4,
   "toc_cell": false,
   "toc_section_display": "block",
   "toc_window_display": false,
   "widenNotebook": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
